name: Test

on:
  - workflow_dispatch
  - push

jobs:
  # https://github.com/swift-actions/setup-swift?tab=readme-ov-file#usage

  test:
    name: Swift ${{ matrix.swift }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        swift: ["5", "6"]
    steps:
      # https://github.com/swift-actions/setup-swift/pull/710
      - uses: swift-actions/setup-swift@next
        with:
          swift-version: ${{ matrix.swift }}
      - uses: actions/checkout@v4
      - name: Build and Test
        run: swift test
