name: Test

on:
  - workflow_dispatch
  - push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # https://github.com/swift-actions/setup-swift/pull/710
      - uses: swift-actions/setup-swift@next
        with:
          swift-version: 6
      - uses: actions/checkout@v4
      - name: Build and Test
        run: swift test
